version: '2'
services:
    jdias-app:
        image: jdias
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jdias-postgresql:5432/JDias
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jdias-elasticsearch:9300
        ports:
            - 8080:8080
    jdias-postgresql:
        extends:
            file: postgresql.yml
            service: jdias-postgresql
    jdias-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jdias-elasticsearch
