package com.sgkhmjaes.jdias.domain.enumeration;

/**
 * The Type enumeration.
 */
public enum Type {
    ACCOUNTDELETION, COMMENT, CONTACT, CONVERSATION, EVENT, EVENTPARTICIPATION, LIKE, LOCATION, MESSAGE, PARTICIPATION, PHOTO, POLL, POLLANSWER, POLLPARTICIPATION, POST, PROFILE, RESHARE, RETRACTION, STATUSMESSAGE
}
